= Introduction

== Shakespeare

Shakespeare is a Java implementation of Screenplay.
It was mainly created to explain the basic concepts of Screenplay and hence is kept rather simple in its core.

To review the code, file issues or suggest changes, please visit the project's link:https://github.com/mkutz/shakespeare[GitHub page].

== Screenplay

A framework helping to write tests like screenplays.
It is based on the ideas from https://ideas.riverglide.com/page-objects-refactored-12ec3541990#.ekkiguobe[Page Objects Refactored] by Antony Marcano, Andy Palmer & John Ferguson Smart, with Jan Molak.

Screenplay does not replace any testing framework like JUnit, TestNG, Spock, RSpec, Jasmine etc.
In fact, it works with any of these.
Screenplay rather structures complex test code in a different way that makes it

- more readably,
- more reusable, and
- more maintainable.

It does that mainly by taking a user-centric and object-oriented view on things.

In screenplay a user is represented by as an _Actor_.
Actors can have _Abilities_.
These enable them to do _Tasks_ or answer _Questions_.

[ditaa]
.Screenplay Core Concepts
....
             answers    +-----------+      about
     /----------------->| Questions |-------------------\
     |                  +-----------+                   |
     |                                                  |
     |                                                  |
     |                                                  v
+-----------+   does    +-----------+           /--------------\
|   Actor   |---------->|   Tasks   |           |    System    |
+-----------+           +-----------+           |  under Test  |
     |                         |                \--------------/
     |has                      |made up of              ^
     |                         |                        |
     v                         v                        |
+-----------+  enable   /-----------\   interact with   |
| Abilities |---------->|  Actions  |-------------------/
+-----------+           \-----------/
....

In screenplay each of these concepts--Actor, Ability, Task and Question--are objects which abstract from the actual actions.

Actions can be calling an API, clicking a link, fetching an email, waiting for something to appear.
All these tiny noisy details are hidden within the Task or Question objects.
