= Actors with Abilities

== Actors

The central object in a Screenplay and Shakespeare is the link:{javadoc-url}/core/org/shakespeareframework/Actor.html[Actor].
Actors represent something or someone that interacts with the system under test.

There can be any number of Actors in a Screenplay (Test).
To make different Actors easily identifiable, they have a name.
The name can be explicitly given or will be randomly assigned.

.Actor with explicitly given name
[source,java,indent=0]
----
include::../../../test/java/ActorDocTest.java[tag=create-actor]
----

.Actor with random name
[source,java,indent=0]
----
include::../../../test/java/ActorDocTest.java[tag=create-actor-random-name]
----

== Abilities

Actors may use link:{javadoc-url}/core/org/shakespeareframework/Ability.html[Abilities] to interact with the system under test.

Ability is a simple marker interface.
Implementations should provide methods providing an object which allows interaction with the system under test.
If that object is being generated on demand or simply wrapped by the Ability is up to the implementation.

.A simple example for an Ability implementation
[source,java,indent=0]
----
include::../../../test/java/Log.java[tag=ability]
----

To allow Actors to use an Ability it needs to be given to them via the link:{javadoc-url}/core/org/shakespeareframework/Actor.html#can(org.shakespeareframework.Ability...)[`can(Ability)` method].

.Give an Ability to an Actor
[source,java,indent=0]
----
include::../../../test/java/AbilityDocTest.java[tag=can]
----

To get an Ability from an Actor, there's the link:{javadoc-url}/core/org/shakespeareframework/Actor.html#uses(java.lang.Class))[`uses(Class<? extends Ability>)` method].

.Get an Ability from an Actor
[source,java,indent=0]
----
include::../../../test/java/AbilityDocTest.java[tag=uses]
----
