= Checking Questions

== Questions

link:{javadoc-url}/core/org/shakespeareframework/Question.html[Questions] are pretty similar to <<Tasks>>, but may return an answer.

They can be checked (answered) by an Actor.
How the Actor finds the answer to a Question is defined in the link:{javadoc-url}/core/org/shakespeareframework/Question.html#answerAs(org.shakespeareframework.Actor)[answerAs(Actor) method] of the Question.

Similar to the link:{javadoc-url}/core/org/shakespeareframework/Task.html#performAs(org.shakespeareframework.Actor)[performAs(Actor) method] of the Task, the Actor is given as an argument, so a Question can use all the Actor's Abilities to find the answer.

.LoggedInState Question
[source,java,indent=0]
----
include::../../../test/java/GroupingInteractionsDocTest.java[tag=question]
----

While it is possible to put complex interactions in Questions it is generally advisable to keep them simple and independent.

=== Good Questions

Undoubtedly good questions do not change the state of the system under test in any way

- Checking a web element is present,
- performing a GET call on an HTTP API and return its body,
- fetching email and retuning its content.

=== Ugly Questions

Doubtfully ugly questions don't change the persisted state of the system under test, but change the local state.
For example the current displayed view.
Using such questions requires to check the state in following Tasks or Questions.

- Navigate to the user's profile page to check for data that is only visible there,
- checking available products by switching to the search results page.

Especially in web applications this type of Questions are often unavoidable, but should be kept to a minimum.

=== Bad Questions

Changing the persistent state of the system under test should genrally be avoided and be left to Tasks.

- Sending data to a backend API,
- login to a web application,
- deleting email.
