= Learning & Remembering Facts

link:{javadoc-url}/core/org/shakespeareframework/Fact.html[Facts] are a way to add data to the link:{javadoc-url}/core/org/shakespeareframework/Actor.html[Actor].
After a Fact was link:{javadoc-url}/core/org/shakespeareframework/Actor.html#learns(org.shakespeareframework.Fact...)[learned], it can always be link:{javadoc-url}/core/org/shakespeareframework/Actor.html#remembers(java.lang.Class)[remembered] by its class and be used to do Tasks or answer Questions.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=learn-fact]

include::../../../test/java/examples/java/FactDocTest.java[tag=remember-fact]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=learn-fact]

include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=remember-fact]
----

Fact classes only need to implement the (empty) Fact marker interface.
Apart from that they can be basically anything but should be immutable value objects or records.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=fact]
----
[source,kotlin,indent=0,role="seconary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=fact]
----

== Relearning Facts

Note that an Actor cannot remember multiple instances of a Fact.
When you call remember with two different instances of the same Fact class, the older one is being forgotten and replaced by the new one.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=learn-fact]

include::../../../test/java/examples/java/FactDocTest.java[tag=relearn-fact]

include::../../../test/java/examples/java/FactDocTest.java[tag=remember-changed-fact]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=learn-fact]

include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=relearn-fact]

include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=remember-changed-fact]
----

== Poly Facts

One way to achieve something similar are Poly Facts: Simply Facts with multiple fields.

E.g. a PhoneNumbers Fact might contain a field for a work phone number and one for a home phone number:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=poly-fact]
----
[source,java,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=poly-fact]
----

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=learn-poly-fact]

include::../../../test/java/examples/java/FactDocTest.java[tag=remember-poly-fact]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=learn-poly-fact]

include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=remember-poly-fact]
----

== Facts with Defaults and Generators

One great advantage of Fact classes is the possibility of adding static fields and methods.

E.g. you can put that one valid test credit card number in a `public static CreditCard DEFAULT` in your `CreditCard` Fact class:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=fact-with-default]
----
[source,kotlin,indent=0,role="seconary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=fact-with-default]
----

Or you can add a method to generate valid unique random email addresses to your `EmailAddress` Fact class:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/FactDocTest.java[tag=fact-with-generator]
----
[source,kotlin,indent=0,role="seconary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/FactDocTest.kt[tag=fact-with-generator]
----

== Personalized Tasks/Questions

Facts can be used to provide an Actor with necessary information for certain Tasks and Questions instead of using <<Tasks with Parameters>>.

By doing so, we can instruct an Actors to do something with their memory as context.

For example, to create an account we usually require a lot of personal information.
To human testers, I can say "go create an account", and they will use their own data to do that.
Using Facts we can achieve the same feel of a personal context.

In that case, an Actors learn their facts in the setup phase of a test.

WARNING: Using Facts in your Tasks and Questions can be a really nice experience.
You don't need to keep your test data at hand in you test code, but can confine it in the test's setup phase.
However, by doing so you might end up scrolling back and forth in order to understand a failing test.
So you really want to limit this to data that is really _owned_ by an Actor.

== Learning by Doing

Another possible use case for Facts is to learn things while doing things.
E.g. after finishing a shop's checkout process it might be useful to remember the displayed order number.

In that case the Facts are learned as a side effect of a Task or a Question.

WARNING: Don't overdo this!
Side effects are not easy to keep track of.
