name: Build PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.adoc'

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - run: ./gradlew check

      - name: cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - run: ./gradlew build jacocoTestReport sonar
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Enable auto merge for Dependabot PRs  
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
