name: Udpate Pages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: pages
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Documentor"
          git config user.email "mail@michael-kutz.de"

      - name: Rebase main
        run: |
          git rebase origin/main
          git pull --rebase
          git push

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Generate manual
        run: |
          ./gradlew asciidoc
          rm -rf docs/manual
          cp -r manual/build/docs/asciidoc docs/manual

      - name: Generate javadocs
        run: |
          ./gradlew javadoc
          rm -rf docs/javadoc
          mkdir docs/javadoc
          cp -r modules/core/build/docs/javadoc docs/javadoc/core
          cp -r modules/selenium/build/docs/javadoc docs/javadoc/selenium
          cp -r modules/retrofit/build/docs/javadoc docs/javadoc/retrofit

      - name: Push changes
        run: |
          git add docs
          git commit -m "Update docs"
          git push
