name: Udpate Pages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - uses: actions/checkout@v2
        with:
          ref: pages
          path: pages

      - name: Update AsciiDoc
        run: |
          ./gradlew asciidoc
          rm -rf pages/docs/${{ github.ref_name }}/manual
          mv manual/build/docs/asciidoc pages/docs/${{ github.ref_name }}/manual

      - name: Update JavaDoc
        run: |
          ./gradlew javadoc
          rm -rf pages/docs/main/javadoc/*
          mv modules/core/build/docs/javadoc pages/docs/${{ github.ref_name }}/javadoc/core
          mv modules/retrofit/build/docs/javadoc pages/docs/${{ github.ref_name }}/javadoc/retrofit
          mv modules/selenium/build/docs/javadoc pages/docs/${{ github.ref_name }}/javadoc/selenium

      - name: Push changes
        run: |
          git config user.name "Documentor"
          git config user.email "mail@michael-kutz.de"
          git add docs
          git commit -m "Update docs"
          git push
        working-directory: pages
