name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

jobs:
  update-gradle:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          overwrite-settings: false

      - uses: actions/checkout@v4
        with:
          ref: update-gradle
          fetch-depth: 0
      
      - run: git rebase main

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
          arguments: wrapper

      - name: Push changes
        run: |
          git config user.name "Gradle Updater"
          git config user.email "mail@michael-kutz.de"
          git add gradle gradlew
          git commit -m "Bump Gradle wrapper to latest"
          git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)

      - name: Open pull request
        run: gh pr create
