name: Update Pages

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'manual/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Create base directory
        run: mkdir -p docs/${{ github.ref_name }}

      - name: Update AsciiDoc
        run: |
          ./gradlew asciidoc
          rm -rf docs/${{ github.ref_name }}/manual
          mv manual/build/docs/asciidoc docs/${{ github.ref_name }}/manual

      - name: Update JavaDoc
        run: |
          ./gradlew javadoc
          rm -rf docs/${{ github.ref_name }}/javadoc
          mkdir docs/${{ github.ref_name }}/javadoc
          mv modules/core/build/docs/javadoc docs/${{ github.ref_name }}/javadoc/core
          mv modules/retrofit/build/docs/javadoc docs/${{ github.ref_name }}/javadoc/retrofit
          mv modules/selenium/build/docs/javadoc docs/${{ github.ref_name }}/javadoc/selenium

      - name: Update "latest" Alias
        if: github.ref_type == 'tag'
        run: |
          rm -f docs/latest
          ln -s ./${{ github.ref_name }} docs/latest

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - id: deployment
        uses: actions/deploy-pages@v1
