name: Update Pages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
  workflow_call:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  update:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Ensure base directory
        run: mkdir -p pages/docs

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Update AsciiDoc
        run: ./update-pages "${{ github.event.inputs.version }}"

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

      - id: deployment
        uses: actions/deploy-pages@v4
