name: Udpate Pages

on:
  workflow_dispatch:
    inputs:
      ref:
        default: main
        description: Tag or branch to generate documentation from
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: pages
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Documentor"
          git config user.email "mail@michael-kutz.de"

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          path: ${{ github.event.inputs.ref }}

      - run: ./gradlew asciidoc javadoc
        working-directory: ${{ github.event.inputs.ref }}

      - name: Push changes
        run: |
          rm -rf docs/${{ github.event.inputs.ref }}
          mv ${{ github.event.inputs.ref }}/docs docs/${{ github.event.inputs.ref }}
          git add docs
          git commit -m "Update docs"
          git push
